### ISSUE TITLE
US#16-Teacher Add Activity Details#17

### ISSUE THREAD

**Issue by theraf01** [theraf01/Tech-Army#18]
### Story Point: 8

**Comment by Prathyushatirunahari** [comment]
**Acceptance criteria** 

•      The teacher should be able to go to the log-in page
•	The teacher should be able to view student details in teacher dashboard
•	The teacher should be to click the activity details page on the teacher dashboard
•	The teacher should be able to view google calendar page after clicking activity details page
•	The teacher should be able to click google calendar 
•	The teacher should be able to add activity details in google calendar
•	The parent should receive the email notification regarding the task
[Uploading Document 11.docx…]()
 
**Task Break down**
- [x] -        Link the teacher dashboard .
- [x] - 	Adding a button of student activity details in the teacher dash board.
- [x] -	Add a google calendar in the web page by clicking student activity details button.
