### ISSUE TITLE
US#7-Enter registration details

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#9]
### Story Point Estimation #13
[US#7-Parent Registration for Kid's activity.pdf](https://github.com/theraf01/Tech-Army/files/4701789/US.7-Parent.Registration.for.Kid.s.activity.pdf)

### Acceptance Criteria for US#7
1.  The parent should be click register here button in the activity/services page.
2.  The parent should be able to go to the log-in page.
3.  The parent should be able to sign-up if a new user to the system.
4.  The parent should be able to login to the system if already signed-up.
5.  The parent should be able to click on the forgot password link.
6.  The parent should be able to login to the system by clicking the login button 
7.  The parent should not be able go to Registration page by clicking in-valid username and password.
8. The parent should be able to go to Registration page by entering valid username and password.
9. The parent should be able to enter registration details like parent name, email address, phone number, student name, student gender, student date of birth, address, activity name, activity session time, age group, image, emergency contact and any allergies/special requirements.
10. The parent should not be able to submit the details if one of the registration details are not filled. 
11. The parent should be able to successfully register to the system if all the registration information is filled in correctly.

### **Task Breakdown:**

- [x] 	Link the log-in page to Register Here button in activity/services page
- [x] 	Create validation of username or password if the user is already registered.
- [x] 	Create a sign-up page if new user to the page.
- [x] 	Validate/check the username and password details in the system to allow submit.
- [x] 	Link the registration form once the username and password are confirmed and validated. 
- [x] 	Create an input detail feature where the parent can enter registration details like parent name, email address, phone number, student name, student gender, student date of birth, address, activity name, activity session time, age group, image, emergency contact and any allergies/special requirements.
- [x] 	Create a validation check if all field are entered correctly.
- [x] 	Create a database, where the parent name, email address, phone number, student name, student gender, student date of birth, address, activity name, activity session time, age group, image, emergency contact and any allergies/special requirements can be stored
- [x] 	Put a “Register” button on the page, so the parent user can submit the registration details to enrol for the activity.

**Comment by theraf01** [comment]
![image](https://user-images.githubusercontent.com/62325456/83533902-4445b680-a544-11ea-829c-1447da474ade.png)
